const LoadingIcon = () => (
    <svg className="loading-icon" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" style={{margin: "auto", background: "none", display: "block", shapeRendering: "auto"}} width="224px" height="224px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <rect x="15.5" y="30" width="9" height="40" fill="#000000">
            <animate attributeName="opacity" dur="2.272727272727273s" repeatCount="indefinite" calcMode="spline" keyTimes="0;0.5;1" keySplines="0.5 0 0.5 1;0.5 0 0.5 1" values="1;0.2;1" begin="-1.3636363636363635"></animate>
        </rect>
        <rect x="35.5" y="30" width="9" height="40" fill="#000000">
            <animate attributeName="opacity" dur="2.272727272727273s" repeatCount="indefinite" calcMode="spline" keyTimes="0;0.5;1" keySplines="0.5 0 0.5 1;0.5 0 0.5 1" values="1;0.2;1" begin="-0.9090909090909092"></animate>
        </rect>
        <rect x="55.5" y="30" width="9" height="40" fill="#000000">
            <animate attributeName="opacity" dur="2.272727272727273s" repeatCount="indefinite" calcMode="spline" keyTimes="0;0.5;1" keySplines="0.5 0 0.5 1;0.5 0 0.5 1" values="1;0.2;1" begin="-0.4545454545454546"></animate>
        </rect>
        <rect x="75.5" y="30" width="9" height="40" fill="#000000">
            <animate attributeName="opacity" dur="2.272727272727273s" repeatCount="indefinite" calcMode="spline" keyTimes="0;0.5;1" keySplines="0.5 0 0.5 1;0.5 0 0.5 1" values="1;0.2;1" begin="-2.272727272727273"></animate>
        </rect>
    </svg>
);
//generated by https://loading.io/
export default LoadingIcon;

