INSERT INTO merchant (merchant_name, email, info, merchant_timestamp) SELECT 'firstMerchant', 'firstmerchant@mail.com', 'Main merchant', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM merchant WHERE merchant_id=1);
INSERT INTO merchant (merchant_name, email, merchant_timestamp) SELECT 'secondMerchant', 'secondmerchant@mail.com', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM merchant WHERE merchant_id=2);

INSERT INTO product (merchant_id, product_name, sex, price, is_available, category, product_timestamp) SELECT 1, 'Fashion Shoes', 'male', 123, TRUE, 'shoes', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product WHERE product_id=1);
INSERT INTO product (merchant_id, product_name, sex, price, is_available, category, product_timestamp) SELECT 1, 'Amazing Pants', 'female', 500, TRUE, 'pants', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product WHERE product_id=2);
INSERT INTO product (merchant_id, product_name, sex, price, is_available, category, product_timestamp) SELECT 2, 'Cool Hat', 'male', 1000, TRUE, 'hat', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product WHERE product_id=3);
INSERT INTO product (merchant_id, product_name, sex, price, is_available, category, product_timestamp) SELECT 2, 'Warm Jacket', 'female', 20000, FALSE, 'jacket', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product WHERE product_id=4);
INSERT INTO product (merchant_id, product_name, sex, price, is_available, category, product_timestamp) SELECT 1, 'Underwear', 'male', 10, FALSE, 'underwear', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product WHERE product_id=5);

INSERT INTO product_attributes (product_id, product_description, color, product_size, brand, material) SELECT 1, 'BLA BLA BLA', 'Black', '42 Eu', 'Not present', 'Canvas' WHERE NOT EXISTS (SELECT * FROM product_attributes WHERE attributes_id=1);
INSERT INTO product_attributes (product_id, product_description, color, product_size, brand) SELECT 2, 'Best choice', 'Blue', 'XS', 'Babibas' WHERE NOT EXISTS (SELECT * FROM product_attributes WHERE attributes_id=2);
INSERT INTO product_attributes (product_id, color, product_size) SELECT 3, 'White', 'M' WHERE NOT EXISTS (SELECT * FROM product_attributes WHERE attributes_id=3);
INSERT INTO product_attributes (product_id, product_description, color, product_size, brand, material) SELECT 4, 'Fits well', 'Yellow', 'XS', 'Like', 'Synthetics' WHERE NOT EXISTS (SELECT * FROM product_attributes WHERE attributes_id=4);

INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 1, TRUE, 'https://localhost/images/thumbnail-shoes.jpg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=1);
INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 1, FALSE, 'https://localhost/images/shoes.jpg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=2);
INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 2, TRUE, 'https://localhost/images/thumbnail-jeans1.jpg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=3);
INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 2, FALSE, 'https://localhost/images/jeans1.jpg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=4);
INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 2, FALSE, 'https://localhost/images/jeans2.jpg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=6);
INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 3, TRUE, 'https://localhost/images/thumbnail-hat.jpg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=7);
INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 3, FALSE, 'https://localhost/images/hat.jpg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=8);
INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 4, TRUE, 'https://localhost/images/thumbnail-jacket.jpg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=9);
INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 4, FALSE, 'https://localhost/images/jacket.jpg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=10);
INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 5, TRUE, 'https://localhost/images/thumbnail-bunny.jpeg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=11);
INSERT INTO product_image (product_id, is_thumbnail, image_path, image_timestamp) SELECT 5, FALSE, 'https://localhost/images/bunny.jpeg', '2024-01-11T14:18:18.778559Z[GMT]' WHERE NOT EXISTS (SELECT * FROM product_image WHERE image_id=12);